topics = [
  # pdf (25)
  { topic: "이메일 첨부 PDF 용량 초과 해결법", category: "pdf" },
  { topic: "학교 과제 PDF 제출 용량 줄이기", category: "pdf" },
  { topic: "계약서 PDF 가볍게 만들기", category: "pdf" },
  { topic: "이력서 PDF 2MB 이하로 줄이기", category: "pdf" },
  { topic: "논문 PDF 압축해서 제출하기", category: "pdf" },
  { topic: "PPT를 PDF로 변환 후 용량 줄이기", category: "pdf" },
  { topic: "스캔한 PDF 용량 줄이기", category: "pdf" },
  { topic: "PDF 여러 개 합치고 압축하기", category: "pdf" },
  { topic: "구글 드라이브 업로드용 PDF 압축", category: "pdf" },
  { topic: "카카오톡 PDF 전송 용량 제한 해결", category: "pdf" },
  { topic: "아이폰에서 PDF 압축하는 법", category: "pdf" },
  { topic: "맥북에서 PDF 용량 줄이기", category: "pdf" },
  { topic: "세금계산서 PDF 용량 줄이기", category: "pdf" },
  { topic: "포트폴리오 PDF 10MB 이하로 만들기", category: "pdf" },
  { topic: "부동산 계약서 PDF 압축 보내기", category: "pdf" },
  { topic: "PDF 비밀번호 설정하기", category: "pdf" },
  { topic: "PDF 페이지 삭제하기", category: "pdf" },
  { topic: "PDF 회전 바로잡기", category: "pdf" },
  { topic: "모바일에서 PDF 압축하기", category: "pdf" },
  { topic: "PDF 흑백으로 변환해 용량 줄이기", category: "pdf" },
  { topic: "한글 파일 PDF로 변환하기", category: "pdf" },
  { topic: "PDF 워터마크 추가하기", category: "pdf" },
  { topic: "공공기관 제출용 PDF 만들기", category: "pdf" },
  { topic: "PDF 인쇄 최적화하기", category: "pdf" },
  { topic: "졸업논문 PDF 제출 용량 맞추기", category: "pdf" },

  # image (20)
  { topic: "인스타그램 업로드용 이미지 압축", category: "image" },
  { topic: "블로그 이미지 용량 줄여 속도 높이기", category: "image" },
  { topic: "카카오톡 원본 사진 용량 줄이기", category: "image" },
  { topic: "회사 로고 이미지 가볍게 만들기", category: "image" },
  { topic: "증명사진 파일 용량 줄이기", category: "image" },
  { topic: "PNG vs JPG 어떤 게 더 가벼울까", category: "image" },
  { topic: "배너 이미지 웹 최적화하기", category: "image" },
  { topic: "네이버 블로그 이미지 최적화", category: "image" },
  { topic: "쇼핑몰 상품 이미지 압축하기", category: "image" },
  { topic: "유튜브 썸네일 최적화", category: "image" },
  { topic: "WebP 변환으로 용량 70% 줄이기", category: "image" },
  { topic: "GIF 용량 줄이기", category: "image" },
  { topic: "RAW 사진 웹용으로 변환하기", category: "image" },
  { topic: "카드뉴스 이미지 최적화", category: "image" },
  { topic: "유튜브 채널아트 이미지 최적화", category: "image" },
  { topic: "온라인 쇼핑몰 대표이미지 최적화", category: "image" },
  { topic: "부동산 매물 사진 압축하기", category: "image" },
  { topic: "여권사진 파일 용량 줄이기", category: "image" },
  { topic: "결혼식 청첩장 이미지 최적화", category: "image" },
  { topic: "배달앱 메뉴 사진 최적화", category: "image" },

  # office (20)
  { topic: "사내 보고서 파일 용량 줄이기", category: "office" },
  { topic: "이메일 첨부파일 20MB 넘길 때 해결법", category: "office" },
  { topic: "회의록 PDF 공유하기", category: "office" },
  { topic: "제안서 파일 가볍게 만들어 보내기", category: "office" },
  { topic: "엑셀을 PDF로 변환 후 압축", category: "office" },
  { topic: "구글슬라이드 PDF 내보내기 최적화", category: "office" },
  { topic: "클라우드 저장용량 아끼는 법", category: "office" },
  { topic: "Slack 파일 업로드 용량 제한 해결", category: "office" },
  { topic: "재택근무 파일 공유 최적화", category: "office" },
  { topic: "Notion 첨부파일 용량 줄이기", category: "office" },
  { topic: "Teams 파일 공유 용량 해결", category: "office" },
  { topic: "Google Workspace 용량 아끼기", category: "office" },
  { topic: "프레젠테이션 파일 경량화", category: "office" },
  { topic: "회사 규정집 PDF 배포하기", category: "office" },
  { topic: "사내 교육자료 파일 최적화", category: "office" },
  { topic: "월간보고서 PDF 이메일 발송", category: "office" },
  { topic: "전자결재 첨부파일 용량 줄이기", category: "office" },
  { topic: "협력사 파일 수신/발신 최적화", category: "office" },
  { topic: "사내 뉴스레터 PDF 최적화", category: "office" },
  { topic: "재무제표 PDF 압축 발송", category: "office" },

  # student (15)
  { topic: "대학교 과제 제출 용량 초과 해결", category: "student" },
  { topic: "수능 원서 파일 용량 줄이기", category: "student" },
  { topic: "학원 교재 PDF 압축", category: "student" },
  { topic: "온라인 강의 자료 파일 최적화", category: "student" },
  { topic: "유학 지원서류 PDF 압축", category: "student" },
  { topic: "교사가 수업자료 PDF 만드는 법", category: "student" },
  { topic: "수행평가 파일 제출 최적화", category: "student" },
  { topic: "교환학생 지원서류 PDF 정리", category: "student" },
  { topic: "온라인 시험 첨부파일 줄이기", category: "student" },
  { topic: "학원 강사 수업자료 PDF 만들기", category: "student" },
  { topic: "EBS 강의 자료 PDF 압축", category: "student" },
  { topic: "논문 심사용 PDF 제출 최적화", category: "student" },
  { topic: "입학원서 PDF 최적화", category: "student" },
  { topic: "방과후 수업 자료 PDF 배포", category: "student" },
  { topic: "장학금 신청서류 PDF 최적화", category: "student" },

  # freelancer (10)
  { topic: "메뉴판 PDF 카톡으로 보내기", category: "freelancer" },
  { topic: "견적서 PDF 가볍게 만들기", category: "freelancer" },
  { topic: "작가 포트폴리오 PDF 최적화", category: "freelancer" },
  { topic: "사진작가 납품 파일 압축", category: "freelancer" },
  { topic: "온라인 쇼핑몰 상품설명서 PDF", category: "freelancer" },
  { topic: "인테리어 견적서 PDF 최적화", category: "freelancer" },
  { topic: "음식점 위생교육 자료 PDF", category: "freelancer" },
  { topic: "프랜차이즈 매뉴얼 PDF 배포", category: "freelancer" },
  { topic: "온라인 강의 교안 PDF 만들기", category: "freelancer" },
  { topic: "부동산 매물 소개서 PDF 최적화", category: "freelancer" },

  # global (10)
  { topic: "How to compress PDF for free online", category: "global" },
  { topic: "Reduce PDF file size without losing quality", category: "global" },
  { topic: "Best free image compressor 2026", category: "global" },
  { topic: "How to compress files before emailing", category: "global" },
  { topic: "Free PDF compressor no watermark", category: "global" },
  { topic: "How to reduce image size for Instagram", category: "global" },
  { topic: "Best PDF compressor for students", category: "global" },
  { topic: "Compress files for Google Drive upload", category: "global" },
  { topic: "How to make PDF smaller on iPhone", category: "global" },
  { topic: "Best free tools to reduce file size 2026", category: "global" }
]

topics.each do |attrs|
  BlogTopic.find_or_create_by!(topic: attrs[:topic]) do |bt|
    bt.category = attrs[:category]
  end
end

puts "Seeded #{BlogTopic.count} blog topics."
