module Admin
  class PostsController < BaseController
    before_action :set_post, only: [:edit, :update, :destroy, :generate, :improve]

    def index
      @posts = Post.recent
      @posts = @posts.where(status: params[:status]) if params[:status].present?
      @posts = @posts.by_category(params[:category]) if params[:category].present?
    end

    def new
      @post = Post.new(status: "draft")
    end

    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to edit_admin_post_path(@post), notice: "Post created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @post.update(post_params)
        redirect_to edit_admin_post_path(@post), notice: "Post updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @post.destroy
      redirect_to admin_posts_path, notice: "Post deleted."
    end

    def generate
      topic = params[:topic].to_s.strip
      if topic.blank?
        redirect_to edit_admin_post_path(@post), alert: "Topic is required."
        return
      end

      result = BlogGeneratorService.new.generate_post(topic, @post.category || "image")
      if result
        @post.update!(result)
        redirect_to edit_admin_post_path(@post), notice: "Content generated by AI."
      else
        redirect_to edit_admin_post_path(@post), alert: "AI generation failed. Check ANTHROPIC_API_KEY."
      end
    end

    def improve
      instruction = params[:instruction].to_s.strip
      if instruction.blank?
        redirect_to edit_admin_post_path(@post), alert: "Instruction is required."
        return
      end

      result = BlogGeneratorService.new.improve_post(@post, instruction)
      if result
        @post.update!(result)
        redirect_to edit_admin_post_path(@post), notice: "Content improved by AI."
      else
        redirect_to edit_admin_post_path(@post), alert: "AI improvement failed."
      end
    end

    def auto_generate
      topic = params[:topic].to_s.strip
      category = params[:category].presence || "image"
      if topic.blank?
        redirect_to admin_posts_path, alert: "Topic is required."
        return
      end

      post = Post.new(status: "draft", category: category)
      result = BlogGeneratorService.new.generate_post(topic, category)
      if result
        post.assign_attributes(result)
        post.save!
        redirect_to edit_admin_post_path(post), notice: "New post generated by AI."
      else
        redirect_to admin_posts_path, alert: "AI generation failed."
      end
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(
        :title_ko, :title_en, :body_ko, :body_en, :slug, :category,
        :status, :published_at, :cover_svg, :meta_description_ko, :meta_description_en,
        :trust_bar, :pain_tag, :error_mockup, :recognition_text, :loss_items, :stats, :subtitle_ko
      )
    end
  end
end
