module Admin
  class PostsController < BaseController
    before_action :set_post, only: [:edit, :update, :destroy, :generate, :improve, :publish]

    def index
      # Loaded unconditionally, not behind the filter: a post stuck at
      # `scheduled` is the one thing on this page nobody went looking for, so it
      # has to appear whichever view is selected. This is the primary channel for
      # that state — the publish-failure email is the secondary one, and this
      # app's production SMTP has already failed once (2026-04-07).
      @stuck_posts = Post.publish_stuck.order(:published_at)

      @posts = Post.recent
      @posts = if params[:status] == "stuck"
        @posts.publish_stuck
      elsif params[:status].present?
        @posts.where(status: params[:status])
      else
        @posts
      end
      @posts = @posts.by_category(params[:category]) if params[:category].present?
    end

    def new
      @post = Post.new(status: "draft")
    end

    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to edit_admin_post_path(@post), notice: "Post created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @post.update(post_params)
        redirect_to edit_admin_post_path(@post), notice: "Post updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @post.destroy
      redirect_to admin_posts_path, notice: "Post deleted."
    end

    def publish
      published_at = params[:published_at].presence&.then { |t| Time.zone.parse(t) } || Time.current
      @post.update!(status: "published", published_at: published_at)
      redirect_back fallback_location: admin_posts_path, notice: "Post published (#{published_at.strftime('%Y-%m-%d %H:%M')})."
    end

    def generate
      topic = params[:topic].to_s.strip
      if topic.blank?
        redirect_to edit_admin_post_path(@post), alert: "Topic is required."
        return
      end

      service = BlogGeneratorService.new
      result = service.generate_post(topic, @post.category || "image")
      if result
        generate_image = result.delete(:_generate_hero_image)
        @post.update!(result)
        service.generate_hero_image(@post) if generate_image
        redirect_to edit_admin_post_path(@post), notice: "Content generated by AI. #{'Hero image generated.' if @post.hero_image.attached?}"
      else
        redirect_to edit_admin_post_path(@post), alert: "AI generation failed. Check ANTHROPIC_API_KEY."
      end
    end

    def improve
      instruction = params[:instruction].to_s.strip
      if instruction.blank?
        redirect_to edit_admin_post_path(@post), alert: "Instruction is required."
        return
      end

      result = BlogGeneratorService.new.improve_post(@post, instruction)
      if result
        @post.update!(result)
        redirect_to edit_admin_post_path(@post), notice: "Content improved by AI."
      else
        redirect_to edit_admin_post_path(@post), alert: "AI improvement failed."
      end
    end

    def auto_generate
      topic = params[:topic].to_s.strip
      category = params[:category].presence || "image"
      if topic.blank?
        redirect_to admin_posts_path, alert: "Topic is required."
        return
      end

      post = Post.new(status: "draft", category: category)
      service = BlogGeneratorService.new
      result = service.generate_post(topic, category)
      if result
        generate_image = result.delete(:_generate_hero_image)
        post.assign_attributes(result)
        post.save!
        service.generate_hero_image(post) if generate_image
        redirect_to edit_admin_post_path(post), notice: "New post generated by AI. #{'Hero image generated.' if post.hero_image.attached?}"
      else
        redirect_to admin_posts_path, alert: "AI generation failed."
      end
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(
        :title_ko, :title_en, :body_ko, :body_en, :slug, :category,
        :status, :published_at, :cover_svg, :meta_description_ko, :meta_description_en,
        :trust_bar, :pain_tag, :error_mockup, :recognition_text, :loss_items, :stats, :subtitle_ko
      )
    end
  end
end
