default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: docpack_development

test:
  <<: *default
  database: docpack_test

production:
  primary:
    <<: *default
    database: docpack_production
  queue:
    <<: *default
    database: docpack_production
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: docpack_production
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: docpack_production
    migrations_paths: db/cable_migrate
