service: docpack

image: chaop2026/docpack

servers:
  web:
    - 5.223.92.4

proxy:
  ssl: false
  host: 5.223.92.4
  app_port: 3000

registry:
  server: ghcr.io
  username: chaop2026
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - DB_PASSWORD
  clear:
    RAILS_ENV: production
    RAILS_LOG_LEVEL: info
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: docpack-db
    DB_PORT: 5432
    DB_USERNAME: docpack
    RAILS_SERVE_STATIC_FILES: true
    WEB_CONCURRENCY: 2

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "docpack_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  db:
    image: postgres:16
    host: 5.223.92.4
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: docpack
        POSTGRES_DB: docpack_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - docpack_pgdata:/var/lib/postgresql/data
